# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 339356eeae986a09b99e569a1f9299e5c09e08320c88e114401a953e553026ec5941836cc620aa6465ec5434c70e395db30d8a93a3b134699c9c83f373e4ecc9

test:
  secret_key_base: cc04ffeaa3335b404acd3ad0fdfafb48a847c1efc719eea2dabddc16d851c1aaf4b136e26569c2ee9250f1024612cfe7bbf7969c5b701ec0d78449b587ce2cac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
